Update Akka.NET and Akka.Hosting to 1.5.0-beta6
akkadotnet/Akka.Persistence.Redis pull request #239
Opened 2023-03-01 04:36 UTC by eaba

2023-03-01 16:38 UTC, Arkatufus requested changes
The Obsolete attributes are not nescessary

2023-03-01 16:38 UTC, Arkatufus commented on src/Akka.Persistence.Redis.Cluster.Tests/Query/RedisCurrentEventsByPersistenceIdSpec.cs
> +        [Obsolete]
You don't need to add these obsolete attributes

2023-03-01 16:48 UTC, eaba commented on src/Akka.Persistence.Redis.Cluster.Tests/Query/RedisCurrentEventsByPersistenceIdSpec.cs
> +        [Obsolete]
ok

2023-03-02 16:09 UTC, Arkatufus commented
The fixture class connection string is not compatible with Redis 7.x

2023-03-02 16:43 UTC, Arkatufus approved these changes

2023-03-02 16:44 UTC, merged